name: Init container build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  IMAGE_REPOSITORY: ghcr.io/micya
  IMAGE_NAME: init-container

  GHCR_PAT: ${{ secrets.GHCR_PAT }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      DOCKERFILE: init-container/Dockerfile
      PATH: init-container

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Generate env variables
      - name: Generate env variables
        run: |
          echo "IMAGE_ID=$IMAGE_REPOSITORY/$IMAGE_NAME" >> $GITHUB_ENV
      # Build docker image
      - name: GitHub container registry login
        run: |
          echo "Logging in to container registry"
          echo $GHCR_PAT | docker login ghcr.io -u USERNAME --password-stdin
      - name: Docker build and push
        run: |
          echo "Building image: $IMAGE_ID"
          docker buildx build -f $DOCKERFILE -t $IMAGE_ID --push $PATH
